import turtle

anh_screen = turtle.Screen()

pencil = turtle.Turtle()
canh = 50
khoangcach = 20
tangsize = 20
pencil.penup()
pencil.goto(-200,0)
pencil.pendown()
pencil.forward(canh)
pencil.left(90)
pencil.forward(canh)
pencil.left(90)
pencil.forward(canh)
pencil.left(90)
pencil.forward(canh)
pencil.left(90)
pencil.left(90)
pencil.penup()
pencil.forward(canh)
pencil.pendown()
pencil.right(30)
pencil.forward(canh)
pencil.right(120)
pencil.forward(canh)

pencil.penup()
pencil.left(60)
pencil.forward(khoangcach)
pencil.left(90)
pencil.forward(tangsize)
pencil.pendown()
pencil.right(90)
pencil.forward(canh+20)
pencil.right(90)
pencil.forward(canh+20)
pencil.right(90)
pencil.forward(canh+20)
pencil.right(90)
pencil.forward(canh+20)
pencil.right(30)
pencil.forward((canh+20))
pencil.right(120)
pencil.forward((canh+20))

pencil.penup()
pencil.left(60)
pencil.forward(khoangcach)
pencil.left(90)
pencil.forward(tangsize)
pencil.pendown()
pencil.right(90)
pencil.forward(canh+40)
pencil.right(90)
pencil.forward(canh+40)
pencil.right(90)
pencil.forward(canh+40)
pencil.right(90)
pencil.forward(canh+40)
pencil.right(30)
pencil.forward((canh+40))
pencil.right(120)
pencil.forward((canh+40))


turtle.done()